### ISSUE TITLE
Hola, la clase está bien pero habría que afinarla.  Te dejo una bateria de pruebas.

### ISSUE THREAD

**Issue by eacevedof** [Axiacore/number-to-letter-java#17]
`Resultados:

string(8) "pruebas:" array(4) { [0]=> string(5) "1.258" [1]=> string(4) "0,58" [2]=> string(6) "120,89" [3]=> string(6) "10.002" } 

amount:1.258, letras:MIL DOSCIENTOS CINCUENTA Y OCHO , con moneda:MIL DOSCIENTOS CINCUENTA Y OCHO PESO

amount:0,58, letras:CINCUENTA Y OCHO , con moneda:PESO CON CINCUENTA Y OCHO PESOS

amount:120,89, letras:CIENTO VEINTE CON OCHENTA Y NUEVE , con moneda:CIENTO VEINTE PESOS CON OCHENTA Y NUEVE PESOS

amount:10.002, letras:CIENTO MIL DOS , con moneda:CIENTO MIL DOS PESOS
string(10) "pruebas 2:" array(4) { [0]=> string(5) "1,258" [1]=> string(4) "0,58" [2]=> string(6) "120,89" [3]=> string(6) "10,002" } 

amount:1,258, letras:UN CON DOSCIENTOS CINCUENTA Y OCHO , con moneda:UN PESO CON DOSCIENTOS CINCUENTA Y OCHO PESOS

amount:0,58, letras:CINCUENTA Y OCHO , con moneda:PESO CON CINCUENTA Y OCHO PESOS

amount:120,89, letras:CIENTO VEINTE CON OCHENTA Y NUEVE , con moneda:CIENTO VEINTE PESOS CON OCHENTA Y NUEVE PESOS

amount:10,002, letras:DIEZ CON DOS , con moneda:DIEZ PESOS CON DOS PESOS`

**Comment by camilonova** [comment]
Hemos separado los repositorios para cada lenguaje de programación
https://github.com/Axiacore/
