### ISSUE TITLE
Algunos cambios para que me funcione en Android

### ISSUE THREAD

**Issue by apterous** [Axiacore/number-to-letter-java#21]
Tenia errores por la coma decimal y algunos temas de espacios etc, les muestro los cambios que hice:

1) Cambie la forma de formatear

String formatedDouble = String.format(Locale.US,"%.2f",doubleNumber);

2) Cambie:

        String splitNumber[] = String.valueOf(doubleNumber).replace('.', '#').split("#");

Por :  String splitNumber[] = formatedDouble.replace('.', '#').split("#");

Use directamente por la variable almacenada en String ya que sino me ponia notacion exponencial para por ejemplo 700 millones

3) Agregue espacios faltantes en la matriz, en los terminos dieciseis etc:

    private static final String[] UNIDADES = { "", "UNO ", "DOS ", "TRES ",
            "CUATRO ", "CINCO ", "SEIS ", "SIETE ", "OCHO ", "NUEVE ", "DIEZ ",
            "ONCE ", "DOCE ", "TRECE ", "CATORCE ", "QUINCE ", "DIECISEIS ",
            "DIECISIETE ", "DIECIOCHO ", "DIECINUEVE ", "VEINTE " };

Saludos!

**Comment by camilonova** [comment]
Hola, este repositorio quedo solamente con codigo JAVA, por favor ajustalo según lo que necesites.
